### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by vainlaind4in** [AmyMialeeMods/no-enchant-cap#37]
Forge 1.19.2
Mod Version: 2.2.4

Gives me:
Exit Code: -1

Happens a couple seconds after launching.

**Comment by AmyMialee** [comment]
need crash logs
exit code is meaningless

**Comment by vainlaind4in** [comment]
Exit code doesn't provide a crash log, as well as launcher not even opening back up after crashing, it opens for a second then just closes most of the time.

I can provide my [latest.log](https://pastebin.com/P2T9d8SK) as the second best thing

**Comment by vainlaind4in** [comment]
I am currently having the same issue with many other mods in my modpack. Is there some sort of universal fix for all of them, or so I need to specifically ask all of them to fix it?

**Comment by vainlaind4in** [comment]
After finally being able to have the launcher open after multiple crashes, the exit code is not -1, but just 1.  I thought it was negative one at first.

**Comment by iforgotmyskin** [comment]
I think this is my crash log 

Exception in thread "main" java.lang.module.ResolutionException: Modules MixinExtras.rc5 and noenchantcap export package com.llamalad7.mixinextras.utils to module forge
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by AmyMialee** [comment]
I'm not sure how to fix it on force, prs welcome, but I don't know.
Forge's including system is a lot more confusing than fabric's.
