### ISSUE TITLE
1.19.2 - Server/Client Cash on startup.

### ISSUE THREAD

**Issue by Wubzzz1337** [AmyMialeeMods/no-enchant-cap#45]
Client just gives me a "Exit Code 1"

On the server it shows this:

```
[15:48:13] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.2.8, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[15:48:13] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.6 by Eclipse Adoptium; OS Linux arch amd64 version 5.15.0-56-generic
[15:48:15] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[15:48:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/fmlcore/1.19.2-43.2.8/fmlcore-1.19.2-43.2.8.jar is missing mods.toml file
[15:48:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/javafmllanguage/1.19.2-43.2.8/javafmllanguage-1.19.2-43.2.8.jar is missing mods.toml file
[15:48:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/lowcodelanguage/1.19.2-43.2.8/lowcodelanguage-1.19.2-43.2.8.jar is missing mods.toml file
[15:48:15] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/mclanguage/1.19.2-43.2.8/mclanguage-1.19.2-43.2.8.jar is missing mods.toml file
[15:48:15] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: /home/container/mods/resourcefullib-forge-1.19.2-1.1.24.jar
[15:48:15] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: botarium. Using Mod File: /home/container/mods/botarium-forge-1.19.2-1.8.2.jar
[15:48:15] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 14 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules noenchantcap and MixinExtras.beta._6 export package com.llamalad7.mixinextras.injector to module refinedstorage
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Server marked as offline...
```

It works fine without this mod.

**Comment by YourLiver** [comment]
Having the same issue, also works fine without the mod. (using MultiMC)

**Comment by Denali007** [comment]
try to use 2.2.6 for 1.19.3, also works on 1.19.2. this worked for me

**Comment by StarkCraft** [comment]
I just attempted it and it crashed my game upon trying to create or load a world by using version 2.2.6 for 1.19.3

> try to use version 2.2.6 for 1.19.3, also works on 1.19.2. this worked for me

**Comment by StarkCraft** [comment]
i have since found out that the issue lies with the compatibility between this mod and inventorio by Lizard_OfOz, each mod works in my modpack individually but i cannot get them to work side by side
