### ISSUE TITLE
1.19.2 Artifacts Mod Incompatibility

### ISSUE THREAD

**Issue by LagByte** [AmyMialeeMods/no-enchant-cap#54]
It would seem this mod and artifacts don't play nice with mixinextras package overlapping. I'm not sure how/why that is or if there is an easy solution (maybe as simple as deleting the overlapping file somehow?), but here is the output log:

Exception in thread "main" java.lang.module.ResolutionException: Modules noenchantcap and MixinExtras.rc5 export package com.llamalad7.mixinextras to module artifacts
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

Any help fixing this would be extremely appreciated!

**Comment by LagByte** [comment]
I updated to the latest version of the mod (although still in MC 1.19.2) for 1.19.3 and it at least lets me launch the game. Now it gives a different error on loading a world. Log attached.

[crash-2023-07-30_00.44.00-client.txt](https://github.com/AmyMialeeMods/no-enchant-cap/files/12208639/crash-2023-07-30_00.44.00-client.txt)

**Comment by LagByte** [comment]
With the 1.19.2 version which gives the first error I posted, I removed artifacts and got the same error then with 'Max Health Fix', removed it and got same error with 'Iron Chests', then again with 'Caelus'. I'm not sure what the problem is, but it is definitely with this mod as the others work together just fine. I think somehow the way this is being exported is overriding the other mods or something along those lines.
